meals/urls.py
from django.urls import path

from .views import *
from users.views import *

app_name='meal'

urlpatterns = [



    path('all_meal/', all_meal, name='all-meal'),
    path('add_meal/', add_meal, name='add-meal'),
    path('update_meal/<int:pk>', updateMeal, name='update-meal'),
    path('delete_meal/<int:pk>', deleteMeal, name='delete-meal'),

    path('week_meal/', weekmenu, name='week-meal'),
    path('preview/', preview, name='preview'),
    path('order/', order, name='order'),
    path('History_order/', orderdeteils, name='order-details'),
    path('user_order/<int:pk>', userorderdetail, name='user-order'),

    path('previous_order_user/', previousorder, name='previous-order-user'),

    path('success/', success, name='success'),




]

menu/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('users/', include('users.urls')),
    path('meals/', include('meals.urls')),
]

users/urls.py
from re import template
from unicodedata import name
from django.urls import path , re_path


from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Login page path
    path('', UserLoginPageView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', UserLogout.as_view(), name='logout'),

    # Home page path
    re_path(r'my_view', my_view, name='my_view'),
 
   


    # User Info
    path('user_info/', user_info, name='user-info'),
    path('update_users/<int:pk>', updateUsers, name='update-users'),
    path('delete_users/<int:pk>', deleteUsers, name='delete-users'),

    #User Page
    
    # path('previous_order_user/', my_view, name='previous-order-user'),

    #reset password
     path('change_password/', MyPasswordChangeView.as_view(),name='password_change'),




]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import DO_NOTHING


# Create your models here.

class UserRole(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name


class Departament(models.Model):
    Departament = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.Departament


class CustomUser(AbstractUser):
    money =models.DecimalField(decimal_places=2, max_digits=20, default=5, blank=True, null=True)
    user_role = models.ForeignKey(UserRole, on_delete=DO_NOTHING, blank=True, null=True)
    Departament = models.ForeignKey(Departament, on_delete=DO_NOTHING, blank=True, null=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column , Submit



class CustomerUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'user_role', 'password1', 'password2' ,'Departament']

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_method='post'
        self.helper.add_input(Submit('Register User','Register User'))

        self.helper.layout = Layout(
            Row(
                Column('username'),
                Column('password1'),
                Column('password2')
            ),
            Row(
                Column('email'),
                Column('user_role')

            ),
            Row(
                Column('first_name'),
                Column('last_name')
            ),
            Row(
                Column('Departament'),
            ),

        )




        
class CustomerUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'user_role','Departament']

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_method='post'
        self.helper.add_input(Submit('Update User','Update User'))

        self.helper.layout = Layout(
            Row(
                Column('username'),
               
            ),
            Row(
                Column('email'),
                Column('user_role')

            ),
            Row(
                Column('first_name'),
                Column('last_name')
            ),
            Row(
                Column('Departament'),
            ),

        )







class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

users/views.py
from django.shortcuts import render, redirect
from .models import  CustomUser
from .forms import *
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView 
from .filters import UsersFilter

# Create your views here.

def my_view(request):
    if request.user.is_superuser:
        return redirect('user-info')
    if request.user:    
      return render(request, 'meals/previous_order.html')




def user_info(request):
 if request.user.is_superuser:
        user_info = CustomUser.objects.all()

        myFilter = UsersFilter(request.GET, queryset=user_info)
        user_info = myFilter.qs

        contex = {'user_info': user_info, 'myFilter': myFilter}

        return render(request, 'users/user_info.html', contex)


class SignUpView(CreateView):
  
        model = CustomUser
        form_class = CustomerUserCreationForm
        success_url = reverse_lazy('signup')
        template_name = 'registration/signup.html'


class UserLoginPageView(LoginView):
    template_name = 'registration/login.html'


class UserLogout(LogoutView):
    template_name = 'registration/login.html'


def updateUsers(request, pk):
 if request.user.is_superuser:
        all_users = CustomUser.objects.get(id=pk)
        form = CustomerUserUpdateForm(instance=all_users)
        if request.method == 'POST':
            form = CustomerUserUpdateForm(request.POST, instance=all_users)
            if form.is_valid():
                form.save()
                return redirect('/users/user_info')
        context = {'form': form}
        return render(request, 'users/update_users.html', context)


def deleteUsers(request, pk):
     if request.user.is_superuser:
        all_users = CustomUser.objects.get(id=pk)
        if request.method == 'POST':
            all_users.delete()
            return redirect('/users/user_info')

        context = {'users': all_users}
        return render(request, 'users/delete_users.html', context)

        

class MyPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change.html'
    success_url = reverse_lazy('password_change')
    

   

    
    

    

users/templates/users_page/base_user.html
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <title>ORDER.IO</title>
  <style>
    body {
      font-family: "Lato", sans-serif;
    }

    /* Fixed sidenav, full height */
    .sidenav {
      height: 100%;
      width: 200px;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #111;
      overflow-x: hidden;
      padding-top: 20px;
    }

    /* Style the sidenav links and the dropdown button */
    .sidenav a,
    .dropdown-btn {
      padding: 6px 8px 6px 16px;
      text-decoration: none;
      font-size: 20px;
      color: #818181;
      display: block;
      border: none;
      background: none;
      width: 100%;
      text-align: left;
      cursor: pointer;
      outline: none;
    }

    /* On mouse-over */
    .sidenav a:hover,
    .dropdown-btn:hover {
      color: #f1f1f1;
    }

    /* Main content */
    .main {
      margin-left: 200px;
      /* Same as the width of the sidenav */
      font-size: 20px;
      /* Increased text to enable scrolling */
      padding: 0px 10px;
    }

    /* Add an active class to the active dropdown button */
    .active {
      color: white;
    }

    /* Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
    .dropdown-container {
      display: none;
      background-color: #262626;
      padding-left: 8px;
    }

    /* Optional: Style the caret down icon */
    .fa-caret-down {
      float: right;
      padding-right: 8px;
    }

    /* Some media queries for responsiveness */
    @media screen and (max-height: 450px) {
      .sidenav {
        padding-top: 15px;
      }

      .sidenav a {
        font-size: 18px;
      }
    }

    #logout_sidebar_button {
      position: absolute;
      display: inline-block;
      bottom: 0;
      left: 15px;
    }
  </style>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body>

  <div class="sidenav">
    <a href="{% url 'meal:previous-order-user' %}">Home</a>
    <a href="{% url 'meal:week-meal' %}">Menu</a>
    <a href="/change_password">Change Password</a>
    <ul id="logout_sidebar_button" class="nav nav-sidebar">
      <li><a href="{% url 'logout'%}">Logout</a></li>
    </ul>
  </div>




  {% block content %}

  {% endblock %}























  <script>
    /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
    var dropdown = document.getElementsByClassName("dropdown-btn");
    var i;

    for (i = 0; i < dropdown.length; i++) {
      dropdown[i].addEventListener("click", function () {
        this.classList.toggle("active");
        var dropdownContent = this.nextElementSibling;
        if (dropdownContent.style.display === "block") {
          dropdownContent.style.display = "none";
        } else {
          dropdownContent.style.display = "block";
        }
      });
    }



  </script>






  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>


</html>

users/templates/users_page/user_page.html
{% extends 'users_page/base_user.html' %}


{% block content %}
<div id="content" , name="content" , class="main">
    <div class="row justify-content-center">
        <div class="center">
            <div>
                <h1>Welcome {{user.username}}</h1>
            </div>



        </div>
    </div>
</div>
{% endblock %}