meals/urls.py
from django.urls import path

from .views import *
from users.views import *

app_name='meal'

urlpatterns = [



    path('all_meal/', all_meal, name='all-meal'),
    path('add_meal/', add_meal, name='add-meal'),
    path('update_meal/<int:pk>', updateMeal, name='update-meal'),
    path('delete_meal/<int:pk>', deleteMeal, name='delete-meal'),

    path('week_meal/', weekmenu, name='week-meal'),
    path('preview/', preview, name='preview'),
    path('order/', order, name='order'),
    path('History_order/', orderdeteils, name='order-details'),
    path('user_order/<int:pk>', userorderdetail, name='user-order'),

    path('previous_order_user/', previousorder, name='previous-order-user'),

    path('success/', success, name='success'),




]

menu/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('users/', include('users.urls')),
    path('meals/', include('meals.urls')),
]

meals/models.py
from django.db import models

from django.db.models import DO_NOTHING
from users.models import CustomUser
# Create your models here.
class Menu(models.Model):

    Day = models.CharField(max_length=100, null=True, blank=True)

    preview = models.BooleanField(default=False)

    def __str__(self):
        return self.Day


class Meal(models.Model):
    CATEGORY = (
        ('Appetizer', 'Appetizer'),
        ('Entree', 'Entree'),
        ('Dessert ', 'Dessert '),
        ('Drinks ', 'Drinks '),

    )

    Food_name = models.CharField(max_length=128, blank=True, null=True)
    Category = models.CharField(max_length=100, null=True, blank=True, choices=CATEGORY)
    Descriptions = models.TextField(max_length=128, blank=True, null=True)
    Price = models.DecimalField(decimal_places=2, max_digits=20, default=0.00, blank=True, null=True)
    menu = models.ManyToManyField(Menu, related_name='weeklymenu', blank=True)

    def __str__(self):
        return self.Food_name

class Order(models.Model):
    customer = models.ForeignKey(CustomUser,default="",on_delete=DO_NOTHING )
    bill = models.DecimalField(max_digits=4 , decimal_places=2)
    date = models.DateTimeField(auto_now_add=True,blank=True)
    number = models.CharField(max_length=60)
    def __str__(self):
        return f"{self.customer} {self.bill}"


class Item(models.Model):
    order = models.ForeignKey(Order,on_delete=DO_NOTHING)
    name  = models.CharField(max_length=120)
    price = models.DecimalField(max_digits=4,decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"{self.order.customer} {self.name} {self.price}"

meals/forms.py
from django import forms
from django.forms import ModelForm

from .models import *

class MealForm(ModelForm):
    class Meta:
        model = Meal
        fields = '__all__'

        

meals/views.py
from django.shortcuts import render, redirect,HttpResponse
from .forms import *
from datetime import date
from django.views.decorators.csrf import csrf_exempt
import random
import json
from .filters import *


# Create your views here.


def randomOrderNumber(length):
    sample = '123456789'
    numberO = ''.join((random.choice(sample) for i in range(length)))
    return numberO


def add_meal(request):
    if request.user.is_superuser:
        form = MealForm
        if request.method == 'POST':
            form = MealForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/meals/all_meal')
        context = {'form': form}
        return render(request, 'meals/add_meal.html', context)


def all_meal(request):
    if request.user.is_superuser:
        all_meal = Meal.objects.all()
        myFilter = MealFilter(request.GET, queryset=all_meal)
        all_meal = myFilter.qs
        context = {'all_meal': all_meal, 'MealFilter': myFilter}
        return render(request, 'meals/all_meal.html', context)


def updateMeal(request, pk):
    if request.user.is_superuser:
        all_meal = Meal.objects.get(id=pk)
        form = MealForm(instance=all_meal)
        if request.method == 'POST':
            form = MealForm(request.POST, instance=all_meal)
            if form.is_valid():
                form.save()
                return redirect('/meals/all_meal')
        context = {'form': form}
        return render(request, 'meals/update_meal.html', context)


def deleteMeal(request, pk):
    if request.user.is_superuser:
        all_meal = Meal.objects.get(id=pk)
        if request.method == 'POST':
            all_meal.delete()
            return redirect('/meals/all_meal')

        context = {'meal': all_meal}
        return render(request, 'meals/delete_meal.html', context)


def weekmenu(request):
  
    if date.today().weekday() == 0:
        WeekMenu = Meal.objects.filter(menu__Day='Monday').values(
            'id', 'Food_name', 'Category', 'Descriptions', 'Price')
    elif date.today().weekday() == 1:
        WeekMenu = Meal.objects.filter(menu__Day='Tuesday').values(
            'id', 'Food_name', 'Category', 'Descriptions', 'Price')
    elif date.today().weekday() == 2:
        WeekMenu = Meal.objects.filter(menu__Day='Wednesday').values(
            'id', 'Food_name', 'Category', 'Descriptions', 'Price')
    elif date.today().weekday() == 3:
        WeekMenu = Meal.objects.filter(menu__Day='Thursday').values(
            'id', 'Food_name', 'Category', 'Descriptions', 'Price')
    elif date.today().weekday() == 4:
        WeekMenu = Meal.objects.filter(menu__Day='Friday').values(
            'id', 'Food_name', 'Category', 'Descriptions', 'Price')
    else:
        return redirect("/meals/preview")
    return render(request, 'meals/WeeklyMenu.html', {'week_meal': WeekMenu})



def preview(request):
 
        display_menu = Meal.objects.filter(menu__preview=True).values(
            'id', 'Food_name', 'Category', 'Descriptions', 'Price')
        return render(request, 'meals/PREVIEW.html', {'week_meal': display_menu})


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


@csrf_exempt
def order(request):
        if request.method == 'POST':
            if is_ajax(request=request):
                request.session['orders'] = request.POST.get('order')
                orders = json.loads(request.session['orders'])
                request.session['bill'] = request.POST.get('total')
                randomNum = randomOrderNumber(6)

                while Order.objects.filter(number=randomNum).count() > 0:
                    randomNum = randomOrderNumber(6)

                if request.user.is_authenticated:
                    order = Order(customer=request.user,
                                number=randomOrderNumber(6),
                                bill=float(request.session['bill']))
                    order.save()
                    request.session['orderNum'] = order.number
                    for article in orders:
                        item = Item(
                            order=order,
                            name=article[0],
                            price=float(article[1])
                        )
                        item.save()

        return render(request, 'meals/order.html')


def success(request):
        orderNum = request.session['orderNum']
        bill = request.session['bill']
        items = Item.objects.filter(order__number=orderNum)
        context = {'order': order, 'bill': bill, 'items': items}
        return render(request, 'meals/success.html', context)


def orderdeteils(request):
    if request.user.is_superuser:
        all_orders = Order.objects.all()

        context = {'orders': all_orders}
        return render(request, 'meals/History_order.html', context)


def userorderdetail(request, pk):
    if request.user.is_superuser:
        user_order = Item.objects.filter(order=pk)
        return render(request, 'meals/more_detail_order.html', {'user_order': user_order})



def previousorder(request):
        user = request.user

        previous_order_m = Item.objects.filter(order__customer=user, order_date__iso_week_day=1)
        
        previous_order_tu = Item.objects.filter(order__customer=user, order_date__iso_week_day=2)
        previous_order_we = Item.objects.filter(order__customer=user, order_date__iso_week_day=3)
        
        
        previous_order_th = Item.objects.filter(order__customer=user, order_date__iso_week_day=4)
        previous_order_f = Item.objects.filter(order__customer=user, order_date__iso_week_day=5)
        
        context={'previous_order_m':previous_order_m,'previous_order_tu':previous_order_tu,'previous_order_we':previous_order_we,
        'previous_order_th':previous_order_th,'previous_order_f':previous_order_f,}

        return render(request, 'meals/previous_order.html', context)

meals/templates/meals/History_order.html
{% extends 'users/base.html'%}

{% block content %}




<style>
    .my-custom-scrollbar {
        position: relative;
        height: 500px;
        overflow: auto;
    }
</style>



<div id="content" , name="content" , class="main">
    <div class="row justify-content-center">
        <div class="center">


            <br>
            <div class="row justify-content-center">
                <div class="center">
                    <h2>Order History </h2>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="table-wrapper-scroll-y my-custom-scrollbar">
                    <div class="card card-body">
                        <table class="table">
                            <tr>
                                <th>User</th>
                                <th>Bill</th>
                                <th>Order Number</th>
                                <th>Date Ordered</th>
                            </tr>

                            {% for order in orders %}

                            <tr>
                                <td>{{order.customer}}</td>
                                <td>{{order.bill}}</td>
                                <td>{{order.number}}</td>
                                <td>{{order.date}}</td>
                                <td><a href="{% url 'meal:user-order' order.id %}">View</a></td>
                            </tr>
                            {% endfor %}

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

meals/templates/meals/PREVIEW.html
{% extends 'users_page/base_user.html' %}


{% block content %}
<div id="content" , name="content" , class="main">
    <div class="row justify-content-center">
        <div class="center">

<div class="row justify-content-center">
    <div class="center">
        <h2> Menu</h2>
    </div>
</div>
<br>
<div class="row">

        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Meal</th>
                    <th>Category</th>
                    <th>Descriptions</th>
                    <th>Price</th>
                </tr>
                {% for meal in week_meal %}
                <tr>
                    <td id="meal{{ meal.id }}">{{meal.Food_name}}</td>
                    <td id="mealCat{{ meal.id }}">{{meal.Category}}</td>
                    <td id="mealDes{{ meal.id }}">{{meal.Descriptions}}</td>
                    <td id="mealPrice{{ meal.id }}">{{meal.Price}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
      </div>
    </div>

</div>
</div>
{% endblock %}

meals/templates/meals/WeeklyMenu.html
{% extends 'users_page/base_user.html' %}


{% block content %}

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(function () {
            $(document).on("click", ".checkRow", function () {
                var getselectedvalues = $(".maintable input:checked").parents("tr").clone().appendTo($(".OrderTable tbody").add(getselectedvalues));
            })
        })


        // $(function(){
        //     $(document).on("click",".deleteorder",function(){
        //        var deleteorderfromtable=$(".OrderTable  input:checked") .parents("tr").remove();
        //     })

        // })

        var orders = JSON.parse(localStorage.getItem('order'))
        var total = localStorage.getItem('total');

        if (orders == null || orders == undefined) {
            localStorage.setItem('order', JSON.stringify([]));
            orders = JSON.parse(localStorage.getItem('order'))
        }

        if (total == null || total == undefined) {
            
            
            
            total = JSON.parse(localStorage.getItem('total'))
        }


    </script>


    <style>
.content-center {
  margin: auto;
  width: 60%;
  padding-left: 30vh;
  padding-top: 100px;
  
}

.next{
    margin: auto;
    padding-top: 0px;
    padding-left: 100vh;
}

.menu{
    padding-top: 0px;
    padding-left: 100vh;
}

    </style>
</head>

<body>
<div class="menu">
    <div class="center">
        <h2> {% now "l" %} Menu</h2>
    </div>

</div>

<div class="next">
    <h2><a href="{% url 'meal:preview'  %}">Next Day menu</a></h2>
</div>
<br>

<div class="content-center">
    <div class="row">

        <div class="col-md-7">
            <div class="card card-body">
                <table class="maintable">
                    <tr>
                        <th>Meal</th>
                        <th>Category</th>
                        <th>Descriptions</th>
                        <th>Price</th>
                        <th>Add</th>

                    </tr>
                    {% for meal in week_meal %}
                    <tr>
                        <td id="meal{{ meal.id }}">{{meal.Food_name}}</td>
                        <td id="mealCat{{ meal.id }}">{{meal.Category}}</td>
                        <td id="mealDes{{ meal.id }}">{{meal.Descriptions}}</td>
                        <td id="mealPrice{{ meal.id }}">{{meal.Price}}</td>
                        <td>
                            <button class="btn-info" onclick="addMeal('{{meal.id}}')">Add Meal</button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>

                <a class="checkRow"  style="height:40px;width:500px" class="btn btn-primary"href="{% url 'meal:order' %}">Save Order</a>

            </div>
        </div>

        <div class="col-mid-5">
            <h2>Order list</h2>
            <div class="card card-body">

                <ul id="mealorder"></ul>

                <h2 id="mealtotal">Total: 0 $</h2>
            </div>
        </div>

    </div>
</div>


<script>

                var mealorder = document.querySelector('#mealorder');
                var mealtotal = document.querySelector('#mealtotal');

                function addMeal(mid) {
                    //get meal name
                    mealId = '#meal' + mid;
                    // mealCat='#mealCat'+mid
                    var Food_name = document.querySelector(mealId).innerHTML;
                    // var Category = document.querySelector(mealCat).innerHTML;
                    //get meal price
                    var mealPrice = '#mealPrice' + mid;
                    var price = document.querySelector(mealPrice).innerHTML;

                    var orders = JSON.parse(localStorage.getItem('order'))
                    var total = localStorage.getItem('total');
                    var OrderList = orders.length;
                    //save meals
                    orders[OrderList] = [Food_name, price];
                    localStorage.setItem('order', JSON.stringify(orders));

                    total = Number(total) + Number(price);
                    localStorage.setItem('total', total);

                    //updating meals in order list 
                    button = '<button class="del"  onclick="removeMeal(' + OrderList + ')">Remove</button>'
                    mealtotal.innerHTML = 'Total:' + total + '$';
                    mealorder.innerHTML += '<li>' + Food_name + ' ' + price + '$' + '' + button + '</li>';
                }
                


                function Myorder() {
                    var orders = JSON.parse(localStorage.getItem('order'))
                    var total = localStorage.getItem('total');
                    var OrderList = orders.length;
                    mealorder.innerHTML = '';
                   
                    for(let i = 0; i < OrderList; i++) {
                        button = '<button class="del"  onclick="removeMeal(' + i + ')">Remove</button>'
                        mealorder.innerHTML += '<li>' + orders[i][0] + ' ' + orders[i][1] + '$' + ' ' + button + '</li>';
                    }
                    mealtotal.innerHTML = 'Total:' + total + '$';
                }
                Myorder();


                function removeMeal(n) {
                    var orders = JSON.parse(localStorage.getItem('order'))
                    var total = localStorage.getItem('total');
                    total = Number(total) - Number(orders[n][1]);
                    orders.splice(n, 1);
                    localStorage.setItem('order', JSON.stringify(orders));
                    localStorage.setItem('total', total);
                    Myorder();



                }



</script>

</body>


{% endblock %}

meals/templates/meals/add_meal.html
{% extends 'users/base.html'%}

{% block content %}



<style>
    #id_long_desc {
    width: 300px;
    height: 200px;
}
</style>
<div id="content" , name="content" , class="main">
    <div class="row justify-content-center">
        <div class="center">

            <div class="row justify-content-center">
                <div class="center">
                    <h2>Add New Meal</h2>
                </div>
            </div>
            <br>
            <div class="long_desc">
                <form action="" method="post" >
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Add New Meal">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

meals/templates/meals/all_meal.html
{% extends 'users/base.html'%}

{% block content %}



<style>
    .my-custom-scrollbar {
        position: relative;
        height: 500px;
        overflow: auto;
    }
</style>



<div id="content" , name="content" , class="main">
    <div class="row justify-content-center">
        <div class="center">
            <div class="row justify-content-center">
                <div class="center">
                    <h2>Meal List</h2>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col">
                    <div class="card card-body">
                        <form method="get">
                            {{MealFilter.form}}
                            <button class="btn btn-primary" type="submit">Search</button>
                        </form>

                    </div>
                </div>
            </div>


            <br>
            <div class="table-wrapper-scroll-y my-custom-scrollbar">
                <div class="card card-body">
                    <table class="table">
                        <tr>

                            <th>Meal</th>
                            <th>Category</th>
                            <th>Descriptions</th>
                            <th>Price</th>
                            <th>Day</th>

                        </tr>
                        {% for meal in all_meal %}
                        <tr>
                            <td><a href="{% url 'meal:update-meal' meal.id %}">Update</a></td>
                            <td><a href="{% url 'meal:delete-meal' meal.id %}">Delete</a></td>
                            <td>{{meal.Food_name}}</td>
                            <td>{{meal.Category}}</td>
                            <td>{{meal.Descriptions}}</td>
                            <td>{{meal.Price}}</td>
                            {% for day in meal.menu.all %}
                            <td>{{day.Day}}</td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                    </table>

                </div>
            </div>


        </div>
    </div>
</div>
{% endblock %}

meals/templates/meals/delete_meal.html
{% extends 'users/base.html'%}

{% block content %}

<div id="content" , name="content" , class="main">
	<div class="row justify-content-center">
		<div class="center">

			<br>
			<div class="row">
				<div class="col-md-6">
					<div class="card card-body">


						<p>Are you sure you want to delete "{{meal}}"?</p>

						<form action="{% url 'meal:delete-meal' meal.id  %}" method="POST">

							{% csrf_token %}
							<a class="btn btn-warning" href="{% url 'meal:all-meal' %}">Cancel</a>

							<input class="btn btn-danger" type="submit" name="Confirm">
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

meals/templates/meals/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <div style="text-align: center;">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <h3 class="text-center">Login</h3>
                <form method="POST">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <input type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" placeholder="***********">
                    </div>
                        <button type="submit" class="btn-info">Login</button>
                
                </form>
            </div>

        </div>
    </div>
</body>

</html>

meals/templates/meals/more_detail_order.html
{% extends 'users/base.html'%}

{% block content %}


<style>
    .my-custom-scrollbar {
        position: relative;
        height: 500px;
        overflow: auto;
    }
</style>


<div id="content" , name="content" , class="main">
    <div class="row justify-content-center">
        <div class="center">


            <br>
            <div class="row justify-content-center">
                <div class="center">
                    <h2>Order</h2>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="table-wrapper-scroll-y my-custom-scrollbar">
                    <div class="card card-body ">
                        <table class="table">
                            <tr>
                                <th>Meal</th>
                                <th>Price</th>
                                <th>Date Ordered</th>
                            </tr>
                            {% for order in user_order %}
                            <tr>
                                <td>{{order.name}}</td>
                                <td>{{order.price}}</td>
                                <td>{{order.order_date}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

meals/templates/meals/my_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="row justify-content-center">
    <div class="center">
        <h2>My order</h2>
    </div>
</div>

<br>
<div class="card card-body" >
    <table class="table">
        <tr>
            <th>Meal</th>
            <th>Category</th>
            <th>Descriptions</th>
            <th>Price</th>
        </tr>
        {% for meal in orders %}
        <tr>
            <td>{{meal.Food_name}}</td>
            <td>{{meal.Category}}</td>
            <td>{{meal.Descriptions}}</td>
            <td>{{meal.Price}}</td>
        </tr>
        {% endfor %}
    </table>
</div>

</body>
</html>

meals/templates/meals/order.html
{% extends 'users_page/base_user.html' %}


{% block content %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


<style>
    .orderstyle{
        padding-left: 85vh;
    }
</style>

<div style="text-align: center;">
    <h2>Order</h2>
        <br>
        <br>

    </div>
    <div class="orderstyle">
        
        <div class="row">
      
                <div class="row">
                    <div style="padding-right: 100px;" class="column" id="food_name">
                        <h3>Meal</h3>

                    </div>
                    <div style="padding-right: 100px;" class="column" id="price">
                        <h3>Price</h3>

                    </div>
                    <div class="column" id="rm">

                    </div>
                </div>


                
            </div>
            <h2 id="total">Total : </h2>
            <button style="padding-right: 80x;" type="submit" class="btn-successs" onclick="Submitorder()">Submit</button>
        </div>
        
    </div>

    <script>

        var food_nam = document.querySelector("#food_name");
        var price = document.querySelector("#price");
        var bill = document.querySelector("#total");
        var rm = document.querySelector("#rm");



        function userorder() {
            var orders = JSON.parse(localStorage.getItem('order'));
            var total = localStorage.getItem('total');
            var OrderList = orders.length;


            food_nam.innerHTML = '<h3>Meal</h3>';
            price.innerHTML = '<h3>Price</h3>';
            rm.innerHTML = '<h3><br></h3>';

            for (let i = 0; i < OrderList; i++) {
                rm.innerHTML += '<h4><button class="del"  onclick="removeOrderMeal(' + i + ')">Remove</button></h4>';
                food_nam.innerHTML += '<h4>' + orders[i][0] + '</4>';
                price.innerHTML += '<h4>' + orders[i][1] + '</4>';
            }
            bill.innerHTML = 'Total: ' + total + ' $';
        }

        userorder();

        function removeOrderMeal(n) {
            var orders = JSON.parse(localStorage.getItem('order'));
            var total = localStorage.getItem('total');
            total = Number(total) - Number(orders[n][1]);
            orders.splice(n, 1);
            localStorage.setItem('order', JSON.stringify(orders));
            localStorage.setItem('total', total);
            userorder();

        }


        function Submitorder() {

            var orders = localStorage.getItem('order');
            var total = localStorage.getItem('total');

            if (total <= 5) {
                var ur = '/meals/order/';
                var orderData = {};
                orderData['order'] = orders;
                orderData['total'] = total;

                $.ajax({
                    url: ur,
                    type: "POST",
                    data: orderData,
                    success: function (data) {
                        window.location.replace('/meals/success')
                        localStorage.setItem('order', JSON.stringify([]));
                        localStorage.setItem('total', 0);
                    }

                })
            }
            else {
                alert("Remove a meal because you don't have enough money");
            }
        }



    </script>

</div>
    

{% endblock %}

meals/templates/meals/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <div style="text-align: center;">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <h3 class="text-center">SignUp</h3>
                <form method="POST">
                    {% csrf_token %}
                    {% for i in form %}
                    <div class="form-group">
                        <div>
                            {{ i.label_tag }}

                        </div>
                        <div>
                            {{ i }}
                        </div>
                        {% if i.help_text %}
                        <small style="color:gray">{{ i.help_text }}</small>
                        {% endif %}
                        {% endfor%}
                        <button type="submit" class="btn-info">SignUp</button>
                    </div>
                </form>
            </div>

        </div>
    </div>




</body>

</html>

meals/templates/meals/success.html
{% extends 'users_page/base_user.html' %}


{% block content %}
<div id="content" , name="content" , class="main">
    <div class="row justify-content-center">
        <div class="center">

            <div style="text-align: center;">
                <br>
                <br>
                <h2>Your order was saved</h2>
             <br>
                
                <div class="card card-body">
                    <table class="table">
                       
                        <tr>
                            <th>Meal</th>
                            <th>Price</th>
                        </tr>
                        <tr>
                            {% for item in items %}
                            <td>{{ item.name }} </td>
                            <td>{{ item.price }}</td>
                            
                        </tr>
                        {% endfor %}
                    </table>
                 
                    <br>
                    <h4> Total : {{ bill }} $</h4>

                    <h4><a href="{% url 'meal:week-meal' %}"> New Order</a></h4>
                </div>

            </div>
        </div>
    </div>

    {% endblock %}

meals/templates/meals/update_meal.html
{% extends 'users/base.html'%}

{% block content %}

<div id="content" , name="content" , class="main">
    <div class="row justify-content-center">
        <div class="center">


            <div class="row justify-content-center">
                <div class="center">
                    <h2>Update Meal</h2>
                </div>
            </div>
            <br>
            <div>
                <form action="" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Update Meal">
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}